spring:
  application:
    name: authservice
server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: animeuser
    password: animepass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: your-very-secure-secret-key
  access-token-expiration: 900000        # 15 minutes
  refresh-token-expiration: 604800000    # 7 days
